export const ENABLE_LOGGING = false;

//general
export const HURT_PUSH_BACK_DELAY = 200;

export const ASSET_PACK_KEYS = {
  MAIN: "MAIN",
} as const;

export const ASSET_KEYS = {
  HERO: "HERO",
  SPIDER: "SPIDER",
  WISP: "WISP",
  ENEMY_DEATH: "ENEMY_DEATH",
  POT: "POT",
  POT_BREAK: "POT_BREAK",
  CHEST: "CHEST",
} as const;

export const DIRECTIONS = {
  DOWN: "DOWN",
  DOWN_LEFT: "DOWN_LEFT",
  DOWN_RIGHT: "DOWN_RIGHT",
  UP: "UP",
  UP_LEFT: "UP_LEFT",
  UP_RIGHT: "UP_RIGHT",
  LEFT: "LEFT",
  RIGHT: "RIGHT",
} as const;

export const INTERACTIVE_OBJECT_TYPE = {
  AUTO: "AUTO",
  PICKUP: "PICKUP",
  OPEN: "OPEN",
} as const;

export const CHEST_STATE = {
  HIDDEN: "HIDDEN",
  REVEALED: "REVEALED",
  OPEN: "OPEN",
} as const;

export const CHEST_FRAME_KEYS = {
  BIG_CHEST_CLOSED: "big_chest_closed",
  SMALL_CHEST_CLOSED: "chest_closed",
  BIG_CHEST_OPEN: "big_chest_open",
  SMALL_CHEST_OPEN: "chest_open",
} as const;

export const CHARACTER_STATES = {
  IDLE_STATE: "IDLE_STATE",
  MOVE_STATE: "MOVE_STATE",
  BOUNCE_MOVE_STATE: "BOUNCE_MOVE_STATE",
  HURT_STATE: "HURT_STATE",
  DEATH_STATE: "DEATH_STATE",
  LIFT_STATE: "LIFT_STATE",
  OPEN_CHEST_STATE: "OPEN_CHEST_STATE",
  IDLE_HOLDING_STATE: "IDLE_HOLDING_STATE",
  MOVE_HOLDING_STATE: "MOVE_HOLDING_STATE",
  THROW_STATE: "THROW_STATE",
  ATTACK_STATE: "ATTACK_STATE",
} as const;

export const CHARACTER_ANIMATIONS = {
  IDLE_DOWN: "IDLE_DOWN",
  IDLE_DOWN_LEFT: "IDLE_DOWN_LEFT",
  IDLE_DOWN_RIGHT: "IDLE_DOWN_RIGHT",
  IDLE_UP: "IDLE_UP",
  IDLE_UP_LEFT: "IDLE_UP_LEFT",
  IDLE_UP_RIGHT: "IDLE_UP_RIGHT",
  IDLE_LEFT: "IDLE_LEFT",
  IDLE_RIGHT: "IDLE_RIGHT",
  WALK_DOWN: "WALK_DOWN",
  WALK_DOWN_LEFT: "WALK_DOWN_LEFT",
  WALK_DOWN_RIGHT: "WALK_DOWN_RIGHT",
  WALK_UP: "WALK_UP",
  WALK_UP_LEFT: "WALK_UP_LEFT",
  WALK_UP_RIGHT: "WALK_UP_RIGHT",
  WALK_LEFT: "WALK_LEFT",
  WALK_RIGHT: "WALK_RIGHT",
  HURT_DOWN: "HURT_DOWN",
  HURT_UP: "HURT_UP",
  HURT_LEFT: "HURT_LEFT",
  HURT_RIGHT: "HURT_RIGHT",
  DIE_DOWN: "DIE_DOWN",
  DIE_UP: "DIE_UP",
  DIE_LEFT: "DIE_LEFT",
  DIE_RIGHT: "DIE_RIGHT",
  IDLE_HOLD_DOWN: "IDLE_HOLD_DOWN",
  IDLE_HOLD_DOWN_LEFT: "IDLE_HOLD_DOWN_LEFT",
  IDLE_HOLD_DOWN_RIGHT: "IDLE_HOLD_DOWN_RIGHT",
  IDLE_HOLD_UP: "IDLE_HOLD_UP",
  IDLE_HOLD_UP_LEFT: "IDLE_HOLD_UP_LEFT",
  IDLE_HOLD_UP_RIGHT: "IDLE_HOLD_UP_RIGHT",
  IDLE_HOLD_LEFT: "IDLE_HOLD_LEFT",
  IDLE_HOLD_RIGHT: "IDLE_HOLD_RIGHT",
  WALK_HOLD_DOWN: "WALK_HOLD_DOWN",
  WALK_HOLD_DOWN_LEFT: "WALK_HOLD_DOWN_LEFT",
  WALK_HOLD_DOWN_RIGHT: "WALK_HOLD_DOWN_RIGHT",
  WALK_HOLD_UP: "WALK_HOLD_UP",
  WALK_HOLD_UP_LEFT: "WALK_HOLD_UP_LEFT",
  WALK_HOLD_UP_RIGHT: "WALK_HOLD_UP_RIGHT",
  WALK_HOLD_LEFT: "WALK_HOLD_LEFT",
  WALK_HOLD_RIGHT: "WALK_HOLD_RIGHT",
  LIFT_DOWN: "LIFT_DOWN",
  LIFT_UP: "LIFT_UP",
  LIFT_LEFT: "LIFT_LEFT",
  LIFT_RIGHT: "LIFT_RIGHT",
} as const;

//hero
export const HERO_START_MAX_HEALTH = 6;
export const HERO_SPEED = 80;
export const HERO_INVULNERABLE_AFTER_HIT_DURATION = 1000;
export const HERO_HURT_PUSH_BACK_SPEED = 50;
export const HERO_ANIMATION_KEYS = {
  IDLE_DOWN: "idle_D",
  IDLE_DOWN_LEFT: "idle_DL",
  IDLE_DOWN_RIGHT: "idle_DR",
  IDLE_UP: "idle_U",
  IDLE_UP_LEFT: "idle_UL",
  IDLE_UP_RIGHT: "idle_UR",
  IDLE_LEFT: "idle_L",
  IDLE_RIGHT: "idle_R",
  WALK_DOWN: "walk_D",
  WALK_DOWN_LEFT: "walk_DL",
  WALK_DOWN_RIGHT: "walk_DR",
  WALK_UP: "walk_U",
  WALK_UP_LEFT: "walk_UL",
  WALK_UP_RIGHT: "walk_UR",
  WALK_LEFT: "walk_L",
  WALK_RIGHT: "walk_R",
  //TODO make animations below
  IDLE_HOLD_DOWN: "idle_D",
  IDLE_HOLD_DOWN_LEFT: "idle_D",
  IDLE_HOLD_DOWN_RIGHT: "idle_D",
  IDLE_HOLD_UP: "idle_D",
  IDLE_HOLD_UP_LEFT: "idle_D",
  IDLE_HOLD_UP_RIGHT: "idle_D",
  IDLE_HOLD_LEFT: "idle_D",
  IDLE_HOLD_RIGHT: "idle_D",
  WALK_HOLD_DOWN: "idle_D",
  WALK_HOLD_DOWN_LEFT: "idle_D",
  WALK_HOLD_DOWN_RIGHT: "idle_D",
  WALK_HOLD_UP: "idle_D",
  WALK_HOLD_UP_LEFT: "idle_D",
  WALK_HOLD_UP_RIGHT: "idle_D",
  WALK_HOLD_LEFT: "idle_D",
  WALK_HOLD_RIGHT: "idle_D",
  LIFT_DOWN: "lift",
  LIFT_UP: "lift",
  LIFT_LEFT: "lift",
  LIFT_RIGHT: "lift",
  HURT_DOWN: "idle_D",
  HURT_UP: "idle_D",
  HURT_LEFT: "idle_D",
  HURT_RIGHT: "idle_D",
  DIE_DOWN: "idle_D",
  DIE_UP: "idle_D",
  DIE_LEFT: "idle_D",
  DIE_RIGHT: "idle_D",
} as const;

//npcs
//enemies
export const ENEMY_SPIDER_MAX_HEALTH = 2;
export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_SPIDER_HURT_PUSH_BACK_SPEED = 50;
export const SPIDER_ANIMATION_KEYS = {
  WALK: "spider_walk",
  HIT: "spider_hit",
  DEATH: ASSET_KEYS.ENEMY_DEATH,
} as const;

export const ENEMY_WISP_MAX_HEALTH = 1;
export const ENEMY_WISP_SPEED = 50;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_X = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_Y = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_DURATION = 500;
export const WISP_ANIMATION_KEYS = {
  IDLE: "wisp_idle",
} as const;
